# Generated by Django 6.0.4 on 2026-04-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=20)),
                ('event_name', models.TextField()),
                ('market_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_type', models.CharField(max_length=50)),
                ('event_type_id', models.CharField(max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('market_open_date', models.DateTimeField(blank=True, null=True)),
                ('market_start_time', models.DateTimeField()),
                ('suspend_time', models.DateTimeField(blank=True, null=True)),
                ('settled_time', models.DateTimeField(blank=True, null=True)),
                ('number_of_winners', models.IntegerField(default=0)),
                ('number_of_active_runners', models.IntegerField(default=0)),
                ('bet_delay', models.IntegerField(default=0)),
                ('market_base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('turn_in_play_enabled', models.BooleanField(default=False)),
                ('persistence_enabled', models.BooleanField(default=False)),
                ('bsp_market', models.BooleanField(default=False)),
                ('bsp_reconciled', models.BooleanField(default=False)),
                ('cross_matching', models.BooleanField(default=False)),
                ('runners_voidable', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('regulators', models.TextField(blank=True, null=True)),
                ('opening_status', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('in_play_seen', models.BooleanField(default=False)),
                ('in_play_start_time', models.DateTimeField(blank=True, null=True)),
                ('total_tick_messages', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'markets',
                'indexes': [models.Index(fields=['event_id'], name='markets_event_i_023538_idx'), models.Index(fields=['event_type_id'], name='markets_event_t_8efd7a_idx'), models.Index(fields=['market_start_time'], name='markets_market__faf234_idx'), models.Index(fields=['status'], name='markets_status_99637d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('price_change_pct', models.DecimalField(decimal_places=5, max_digits=8)),
                ('momentum', models.DecimalField(decimal_places=5, max_digits=8)),
                ('volatility', models.DecimalField(decimal_places=5, max_digits=8)),
                ('trend_slope', models.DecimalField(decimal_places=7, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=5, max_digits=8)),
                ('tick_count', models.SmallIntegerField()),
                ('duration_sec', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feature_version', models.CharField(default='v1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='betapp.market')),
            ],
            options={
                'db_table': 'feature_vectors',
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.BigIntegerField()),
                ('runner_name', models.CharField(max_length=255)),
                ('sort_priority', models.SmallIntegerField(default=0)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('final_result', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('opening_win_prob', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('closing_win_prob', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('highest_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price_range', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_ticks', models.IntegerField(default=0)),
                ('pre_match_ticks', models.IntegerField(default=0)),
                ('in_play_ticks', models.IntegerField(default=0)),
                ('first_tick_time', models.DateTimeField(blank=True, null=True)),
                ('last_tick_time', models.DateTimeField(blank=True, null=True)),
                ('in_play_first_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('in_play_last_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('in_play_min_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('in_play_max_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='betapp.market')),
            ],
            options={
                'db_table': 'runners',
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp', models.DecimalField(decimal_places=3, max_digits=10)),
                ('traded_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tick_time', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ticks', to='betapp.market')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ticks', to='betapp.runner')),
            ],
            options={
                'db_table': 'price_ticks',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('label', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('NEUTRAL', 'NEUTRAL')], max_length=10)),
                ('tick_count', models.SmallIntegerField()),
                ('feature_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='betapp.featurevector')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='betapp.market')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='betapp.runner')),
            ],
            options={
                'db_table': 'patterns',
            },
        ),
        migrations.AddField(
            model_name='featurevector',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='betapp.runner'),
        ),
        migrations.AddIndex(
            model_name='runner',
            index=models.Index(fields=['market'], name='runners_market__98d3af_idx'),
        ),
        migrations.AddIndex(
            model_name='runner',
            index=models.Index(fields=['selection_id'], name='runners_selecti_4d2eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='runner',
            index=models.Index(fields=['status'], name='runners_status_c8297c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together={('market', 'selection_id')},
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['runner', '-tick_time'], name='price_ticks_runner__562add_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['market', '-tick_time'], name='price_ticks_market__c95574_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['tick_time'], name='price_ticks_tick_ti_2f2bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['runner', 'label'], name='patterns_runner__baf747_idx'),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['market', 'label'], name='patterns_market__6d7715_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevector',
            index=models.Index(fields=['runner', 'window_end'], name='feature_vec_runner__1409f0_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevector',
            index=models.Index(fields=['market', 'window_end'], name='feature_vec_market__c41211_idx'),
        ),
    ]
