# Generated by Django 6.0.4 on 2026-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_convert_price_ticks_to_hypertable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricetick',
            constraint=models.UniqueConstraint(fields=('runner', 'tick_time'), name='uq_price_ticks_runner_tick_time'),
        ),
    ]
