# Generated by Django 6.0.4 on 2026-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0003_pricetick_uq_price_ticks_runner_tick_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricetick',
            name='uq_price_ticks_runner_tick_time',
        ),
        migrations.AddField(
            model_name='pricetick',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricetick',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricetick',
            name='phase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricetick',
            name='snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricetick',
            name='win_prob',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pricetick',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['year', 'month', 'day'], name='price_ticks_year_82950e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetick',
            index=models.Index(fields=['phase'], name='price_ticks_phase_ae952e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricetick',
            constraint=models.UniqueConstraint(fields=('runner', 'tick_time', 'snapshot'), name='uq_price_ticks_runner_tick_time_snapshot'),
        ),
    ]
