# Generated by Django 6.0.4 on 2026-04-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0004_remove_pricetick_uq_price_ticks_runner_tick_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pricetick',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='runner',
            options={'managed': False},
        ),
    ]
