# Generated by Django 6.0.4 on 2026-04-11 11:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0005_alter_market_options_alter_pricetick_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('player_name', models.CharField(db_index=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicketkeeper', 'Wicketkeeper'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('ipl_debut', models.DateField(blank=True, null=True)),
                ('last_season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'players',
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='IPLMatch',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('season', models.PositiveSmallIntegerField(db_index=True)),
                ('match_number', models.PositiveIntegerField(blank=True, null=True)),
                ('match_date', models.DateField(db_index=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('team_home', models.CharField(db_index=True, max_length=255)),
                ('team_away', models.CharField(db_index=True, max_length=255)),
                ('toss_winner', models.CharField(blank=True, max_length=255, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=20, null=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('win_by_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('win_by_wickets', models.PositiveIntegerField(blank=True, null=True)),
                ('player_of_match', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ipl_matches',
                'ordering': ['-match_date', 'match_number'],
                'indexes': [models.Index(fields=['season', 'match_date'], name='ipl_matches_season_550ec7_idx'), models.Index(fields=['team_home'], name='ipl_matches_team_ho_166fd3_idx'), models.Index(fields=['team_away'], name='ipl_matches_team_aw_9f4c90_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('batting_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='betapp.iplmatch')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_appearances', to='betapp.player')),
            ],
            options={
                'db_table': 'match_players',
                'indexes': [models.Index(fields=['match', 'team_name'], name='match_playe_match_i_fc1375_idx'), models.Index(fields=['player'], name='match_playe_player__fb567f_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('innings', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('over_number', models.PositiveSmallIntegerField()),
                ('ball_number', models.PositiveSmallIntegerField()),
                ('runs_batter', models.PositiveSmallIntegerField(default=0)),
                ('runs_extras', models.PositiveSmallIntegerField(default=0)),
                ('runs_total', models.PositiveSmallIntegerField(default=0)),
                ('extra_type', models.CharField(blank=True, choices=[('wide', 'wide'), ('noball', 'noball'), ('legbye', 'legbye'), ('bye', 'bye')], max_length=20, null=True)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='betapp.iplmatch')),
                ('batter', models.ForeignKey(db_column='batter_id', on_delete=django.db.models.deletion.PROTECT, related_name='balls_faced_records', to='betapp.player')),
                ('bowler', models.ForeignKey(db_column='bowler_id', on_delete=django.db.models.deletion.PROTECT, related_name='balls_bowled_records', to='betapp.player')),
                ('non_striker', models.ForeignKey(db_column='non_striker_id', on_delete=django.db.models.deletion.PROTECT, related_name='non_striker_records', to='betapp.player')),
                ('player_out', models.ForeignKey(blank=True, db_column='player_out_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissal_records', to='betapp.player')),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['match', 'innings', 'over_number', 'ball_number', 'delivery_id'],
                'indexes': [models.Index(fields=['match', 'innings', 'over_number', 'ball_number'], name='deliveries_match_i_377e66_idx'), models.Index(fields=['batter'], name='deliveries_batter__6e27e2_idx'), models.Index(fields=['bowler'], name='deliveries_bowler__3d5ab7_idx'), models.Index(fields=['player_out'], name='deliveries_player__c533c5_idx'), models.Index(fields=['is_wicket'], name='deliveries_is_wick_3c04f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerIPLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_short', models.CharField(blank=True, max_length=20, null=True)),
                ('season', models.PositiveSmallIntegerField(db_index=True)),
                ('is_current', models.BooleanField(default=False)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='ipl_teams', to='betapp.player')),
            ],
            options={
                'db_table': 'player_ipl_teams',
                'indexes': [models.Index(fields=['season'], name='player_ipl__season_c86374_idx'), models.Index(fields=['team_name'], name='player_ipl__team_na_1a0d0f_idx'), models.Index(fields=['player', 'season'], name='player_ipl__player__587c64_idx')],
                'unique_together': {('player', 'team_name', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchBatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.PositiveSmallIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dismissal_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('is_not_out', models.BooleanField(default=False)),
                ('batting_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='batting_scorecards', to='betapp.iplmatch')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_batting', to='betapp.player')),
            ],
            options={
                'db_table': 'player_match_batting',
                'indexes': [models.Index(fields=['player'], name='player_matc_player__cdbcd0_idx'), models.Index(fields=['match'], name='player_matc_match_i_d4a08e_idx'), models.Index(fields=['innings'], name='player_matc_innings_7c559f_idx')],
                'unique_together': {('match', 'player', 'innings')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchBowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.PositiveSmallIntegerField()),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('runs_given', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('economy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('wides', models.PositiveIntegerField(default=0)),
                ('noballs', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scorecards', to='betapp.iplmatch')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_bowling', to='betapp.player')),
            ],
            options={
                'db_table': 'player_match_bowling',
                'indexes': [models.Index(fields=['player'], name='player_matc_player__e26578_idx'), models.Index(fields=['match'], name='player_matc_match_i_1a9441_idx'), models.Index(fields=['innings'], name='player_matc_innings_8f9cc5_idx')],
                'unique_together': {('match', 'player', 'innings')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSituationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('powerplay', 'powerplay'), ('middle', 'middle'), ('death', 'death')], max_length=20)),
                ('innings_type', models.CharField(choices=[('chasing', 'chasing'), ('defending', 'defending')], max_length=20)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('boundary_count', models.PositiveIntegerField(default=0)),
                ('boundary_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('wickets_lost', models.PositiveIntegerField(default=0)),
                ('dismissal_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='situation_stats', to='betapp.player')),
            ],
            options={
                'db_table': 'player_situation_stats',
                'indexes': [models.Index(fields=['player'], name='player_situ_player__b881a4_idx'), models.Index(fields=['phase'], name='player_situ_phase_081a8d_idx'), models.Index(fields=['innings_type'], name='player_situ_innings_d3e6d9_idx')],
                'unique_together': {('player', 'phase', 'innings_type')},
            },
        ),
    ]
