# Generated by Django 6.0.4 on 2026-04-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0006_player_iplmatch_matchplayer_delivery_playeriplteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDelivery',
            fields=[
                ('live_delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='cricbuzz', max_length=50)),
                ('source_match_id', models.CharField(db_index=True, max_length=50)),
                ('innings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('over_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ball_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('batter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bowler_name', models.CharField(blank=True, max_length=255, null=True)),
                ('non_striker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('runs_batter', models.PositiveSmallIntegerField(default=0)),
                ('runs_extras', models.PositiveSmallIntegerField(default=0)),
                ('runs_total', models.PositiveSmallIntegerField(default=0)),
                ('extra_type', models.CharField(blank=True, choices=[('wide', 'wide'), ('noball', 'noball'), ('legbye', 'legbye'), ('bye', 'bye')], max_length=20, null=True)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_kind', models.CharField(blank=True, max_length=50, null=True)),
                ('player_out_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('event_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batter', models.ForeignKey(blank=True, db_column='batter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_balls_faced', to='betapp.player')),
                ('bowler', models.ForeignKey(blank=True, db_column='bowler_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_balls_bowled', to='betapp.player')),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='live_deliveries', to='betapp.iplmatch')),
                ('non_striker', models.ForeignKey(blank=True, db_column='non_striker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_non_striker_balls', to='betapp.player')),
                ('player_out', models.ForeignKey(blank=True, db_column='player_out_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_dismissal_records', to='betapp.player')),
            ],
            options={
                'db_table': 'live_deliveries',
                'ordering': ['match', 'innings', 'over_number', 'ball_number', 'live_delivery_id'],
                'indexes': [models.Index(fields=['match', 'innings', 'over_number', 'ball_number'], name='live_delive_match_i_af94f2_idx'), models.Index(fields=['source_match_id'], name='live_delive_source__1139d2_idx'), models.Index(fields=['updated_at'], name='live_delive_updated_d27dee_idx'), models.Index(fields=['is_confirmed'], name='live_delive_is_conf_bbfb5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveMatchState',
            fields=[
                ('live_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='cricbuzz', max_length=50)),
                ('source_match_id', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('innings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('batting_team', models.CharField(blank=True, max_length=255, null=True)),
                ('bowling_team', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('current_run_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('required_run_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target', models.PositiveIntegerField(blank=True, null=True)),
                ('toss_winner', models.CharField(blank=True, max_length=255, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=20, null=True)),
                ('partnership_runs', models.PositiveIntegerField(default=0)),
                ('partnership_balls', models.PositiveIntegerField(default=0)),
                ('recent_overs', models.CharField(blank=True, max_length=255, null=True)),
                ('last5_overs_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('last5_overs_wickets', models.PositiveIntegerField(blank=True, null=True)),
                ('last3_overs_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('powerplay_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('powerplay_from', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('powerplay_to', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('latest_ball_text', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='live_states', to='betapp.iplmatch')),
            ],
            options={
                'db_table': 'live_match_states',
                'indexes': [models.Index(fields=['match'], name='live_match__match_i_d14eea_idx'), models.Index(fields=['source_match_id'], name='live_match__source__ee671d_idx'), models.Index(fields=['fetched_at'], name='live_match__fetched_9fb18f_idx')],
            },
        ),
    ]
