# Generated by Django 6.0.4 on 2026-04-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0007_livedelivery_livematchstate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('match', 'innings', 'over_number', 'ball_number'), name='unique_delivery_per_ball'),
        ),
    ]
