# Generated by Django 6.0.4 on 2026-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0008_delivery_unique_delivery_per_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cricbuzz_profile_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cricbuzz_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='debut_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['player_name'], name='players_player__eeabf1_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['normalized_name'], name='players_normali_0e08ea_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['nationality'], name='players_nationa_28e48b_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['role'], name='players_role_4e55e1_idx'),
        ),
    ]
