# Generated by Django 6.0.4 on 2026-04-17 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0009_player_cricbuzz_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='duration_sec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='market_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='momentum',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='price_at_end',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='price_at_start',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='price_change_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='price_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='price_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='runner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='runner_won',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='trend_slope',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='volatility',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='window_end_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='window_start_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='window_start_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='feature_vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='betapp.featurevector'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='market',
            field=models.ForeignKey(db_column='market_id', on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='betapp.market'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='runner',
            field=models.ForeignKey(db_column='runner_id', on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='betapp.runner'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='tick_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['pattern_type'], name='patterns_pattern_571fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['window_start'], name='patterns_window__69b223_idx'),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['window_end'], name='patterns_window__c9462b_idx'),
        ),
    ]
