# Generated by Django 6.0.4 on 2026-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0011_alter_delivery_options_alter_iplmatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplmatch',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='team1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='team2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='toss_decision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
