# Generated by Django 6.0.4 on 2026-04-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0012_iplmatch_status_iplmatch_team1_iplmatch_team2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('market_id', models.CharField(db_index=True, max_length=100)),
                ('runner_id', models.CharField(db_index=True, max_length=100)),
                ('striker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.CharField(blank=True, max_length=50, null=True)),
                ('innings_type', models.CharField(blank=True, max_length=50, null=True)),
                ('final_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('signal', models.CharField(max_length=20)),
                ('model_source', models.CharField(default='betpredict_model.pkl', max_length=100)),
                ('raw_features', models.JSONField(blank=True, default=dict)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, db_column='match_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='betapp.iplmatch')),
            ],
            options={
                'db_table': 'signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['market_id'], name='signals_market__bc9139_idx'), models.Index(fields=['runner_id'], name='signals_runner__e7a1c7_idx'), models.Index(fields=['created_at'], name='signals_created_9748c6_idx')],
            },
        ),
    ]
