# Generated by Django 6.0.4 on 2026-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0013_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMarketTick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('market_id', models.CharField(db_index=True, max_length=50)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_type', models.CharField(blank=True, max_length=100, null=True)),
                ('market_time', models.DateTimeField(blank=True, null=True)),
                ('runner_id', models.CharField(db_index=True, max_length=50)),
                ('runner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time_ms', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('publish_time_utc', models.DateTimeField(blank=True, null=True)),
                ('ltp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prev_ltp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price_change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('market_status', models.CharField(blank=True, max_length=50, null=True)),
                ('in_play', models.BooleanField(default=False)),
                ('bet_delay', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('settled_time', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('month', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, default='market_ws_async', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_market_ticks',
                'indexes': [models.Index(fields=['market_id', 'runner_id'], name='live_market_market__bb1515_idx'), models.Index(fields=['publish_time_utc'], name='live_market_publish_c19f75_idx'), models.Index(fields=['year', 'month'], name='live_market_year_859a4a_idx'), models.Index(fields=['market_status'], name='live_market_market__d62ebc_idx')],
            },
        ),
    ]
