# Generated by Django 6.0.4 on 2026-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0014_livemarkettick'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='livemarkettick',
            name='live_market_market__bb1515_idx',
        ),
        migrations.RemoveIndex(
            model_name='livemarkettick',
            name='live_market_publish_c19f75_idx',
        ),
        migrations.RemoveIndex(
            model_name='livemarkettick',
            name='live_market_year_859a4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='livemarkettick',
            name='live_market_market__d62ebc_idx',
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='ltp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='market_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='prev_ltp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='price_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='price_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='price_direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='publish_time_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='runner_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livemarkettick',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='livemarkettick',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='livemarkettick',
            name='source',
        ),
    ]
