# Generated by Django 6.0.4 on 2026-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0015_remove_livemarkettick_live_market_market__bb1515_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplmatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='market_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='match_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='open_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='open_date_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='player_of_match',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='result_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='result_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='team1_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='team2_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='winning_margin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
