# import os
# import pickle
# import numpy as np


# BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# MODEL_PATH = os.path.join(BASE_DIR, "betpredict_model.pkl")

# with open(MODEL_PATH, "rb") as f:
#     pkg = pickle.load(f)

# model = pkg["model"]
# feat_cols = pkg["feature_cols"]

# THRESHOLD = 0.65


# # ══════════════════════════════════════════════════════════════
# # PATTERN LIBRARY — loaded dynamically from patterns_library.json
# # Run update_patterns.py to regenerate with new data
# # ══════════════════════════════════════════════════════════════

# def _load_pattern_library() -> dict:
#     """
#     Load pattern library from JSON file.
#     Falls back to empty structure if file not found.
#     JSON is generated by update_patterns.py from features_dataset.csv
#     """
#     # Look for patterns_library.json relative to this file
#     search_paths = [
#         os.path.join(BASE_DIR, "patterns_library.json"),
#         os.path.join(BASE_DIR, "data", "patterns_library.json"),
#         os.path.join(BASE_DIR, "..", "data", "patterns_library.json"),
#         os.path.join(BASE_DIR, "..", "data", "parsed", "patterns_library.json"),
#     ]

#     for path in search_paths:
#         if os.path.exists(path):
#             with open(path, "r") as f:
#                 data = json.load(f)
#             lib = data.get("library", data)
#             print(f"[PatternLibrary] Loaded from {path} — {sum(len(c['patterns']) for c in lib.values())} patterns")
#             return lib

#     print("[PatternLibrary] WARNING: patterns_library.json not found — run update_patterns.py")
#     return {}


# import json as _json_module
# import json
# PATTERN_LIBRARY = _load_pattern_library()


# # ══════════════════════════════════════════════════════════════
# # DETECT PATTERN — priority order, strongest signal first
# # ══════════════════════════════════════════════════════════════

# def detect_pattern(features: dict) -> dict:

#     over             = features.get("over", 0)
#     is_powerplay     = features.get("is_powerplay", 0)
#     is_middle        = features.get("is_middle", 0)
#     is_death         = features.get("is_death", 0)
#     is_innings_2     = features.get("is_innings_2", 0)
#     last_ball_wicket = features.get("last_ball_wicket", 0)
#     last_ball_six    = features.get("last_ball_six", 0)
#     rolling_3_wkts   = features.get("rolling_3_wickets", 0)
#     rolling_3_runs   = features.get("rolling_3_runs", 0)
#     rolling_6_runs   = features.get("rolling_6_runs", 0)
#     rolling_6_dots   = features.get("rolling_6_dots", 0)
#     rolling_6_bdry   = features.get("rolling_6_boundaries", 0)
#     batting_momentum = features.get("batting_momentum", 0)
#     wickets_before   = features.get("wickets_before", 0)
#     wickets_in_hand  = features.get("wickets_in_hand", 10)
#     crr              = features.get("current_run_rate", 0)
#     rrr              = features.get("required_rate", 0)
#     ltp              = features.get("price", 2.0)
#     pdiff            = features.get("price_trend_3", 0)
#     pp_runs          = features.get("pp_runs", 0)

#     # ── WICKET PATTERNS ──────────────────────────────────────
#     if wickets_before >= 7 and is_death:
#         return _b("WICKET_PATTERNS", "TAIL_EXPOSED",
#             f"{wickets_before} wickets down · Death overs · {int(wickets_in_hand)} left")

#     if rolling_3_wkts >= 3 and is_middle:
#         return _b("WICKET_PATTERNS", "MIDDLE_COLLAPSE",
#             f"{int(rolling_3_wkts)} wickets in middle overs · Over {over}")

#     if rolling_3_wkts >= 3:
#         return _b("WICKET_PATTERNS", "WICKET_COLLAPSE",
#             f"{int(rolling_3_wkts)} wickets last 3 overs · {int(wickets_in_hand)} in hand")

#     if last_ball_wicket == 1 and is_powerplay:
#         return _b("WICKET_PATTERNS", "POWERPLAY_WICKET",
#             f"Wicket in powerplay · Over {over}")

#     if last_ball_wicket == 1:
#         return _b("WICKET_PATTERNS", "WICKET_SPIKE",
#             f"Wicket just fell · Over {over} · {int(wickets_in_hand)} left")

#     # ── PRESSURE PATTERNS ────────────────────────────────────
#     if is_innings_2 and rrr > 0 and crr > 0 and (rrr - crr) >= 2:
#         return _b("PRESSURE_PATTERNS", "CHASE_CRISIS",
#             f"Required {rrr:.1f} vs Current {crr:.1f} · Chase behind")

#     if is_innings_2 and rrr > 0 and crr > 0 and (crr - rrr) >= 2:
#         return _b("PRESSURE_PATTERNS", "CHASE_CONTROLLED",
#             f"Current {crr:.1f} above required {rrr:.1f} · Chase in control")

#     if is_middle and rrr > 12:
#         return _b("PRESSURE_PATTERNS", "RUN_RATE_DANGER",
#             f"Required rate {rrr:.1f} · Middle overs · High pressure")

#     if rolling_6_dots >= 5:
#         return _b("PRESSURE_PATTERNS", "DOT_BALL_TRAP",
#             f"{int(rolling_6_dots)} dot balls in last 6 · Batting stifled")

#     if rolling_6_dots >= 4:
#         return _b("PRESSURE_PATTERNS", "PRESSURE_BUILD",
#             f"{int(rolling_6_dots)} dot balls in last 6 · Pressure mounting")

#     # ── PHASE PATTERNS ────────────────────────────────────────
#     if is_death and over >= 17 and rolling_6_runs >= 15:
#         return _b("PHASE_PATTERNS", "DEATH_CARNAGE",
#             f"{rolling_6_runs:.0f} runs in last 2 overs · Over {over}")

#     if is_powerplay and pp_runs >= 50 and wickets_before <= 1:
#         return _b("PHASE_PATTERNS", "POWERPLAY_DOMINANT",
#             f"{pp_runs} runs in powerplay · {wickets_before} wicket(s) · Dominant")

#     if is_middle and rolling_6_runs < 20 and 2 <= wickets_before <= 4:
#         return _b("PHASE_PATTERNS", "MIDDLE_GRIND",
#             f"Slow middle overs · {rolling_6_runs:.0f} runs · {wickets_before} wickets")

#     # ── BATTING PATTERNS ─────────────────────────────────────
#     if rolling_6_bdry >= 3 and last_ball_six >= 1:
#         return _b("BATTING_PATTERNS", "SIX_STORM",
#             f"Sixes flying · {int(rolling_6_bdry)} boundaries · Over {over}")

#     if rolling_6_bdry >= 3:
#         return _b("BATTING_PATTERNS", "BOUNDARY_BURST",
#             f"{int(rolling_6_bdry)} boundaries in last 6 · Over {over}")

#     if is_powerplay and rolling_6_bdry >= 2:
#         return _b("BATTING_PATTERNS", "POWERPLAY_SURGE",
#             f"{int(rolling_6_bdry)} boundaries in powerplay · Strong start")

#     if is_death and wickets_before >= 5 and batting_momentum > 0.5:
#         return _b("BATTING_PATTERNS", "DEATH_REVIVAL",
#             f"Over {over} · {wickets_before} wickets but scoring · Revival")

#     if is_death and batting_momentum > 1.0:
#         return _b("BATTING_PATTERNS", "DEATH_SLOG",
#             f"Over {over} · Death · {rolling_3_runs:.0f} runs last 3 overs")

#     if batting_momentum > 2.0 and rolling_3_runs >= 15:
#         return _b("BATTING_PATTERNS", "BATTING_SURGE",
#             f"{rolling_3_runs:.0f} runs in last 3 overs · Strong momentum")

#     # ── PRICE PATTERNS ────────────────────────────────────────
#     if ltp > 2.5 and pdiff > 0.05:
#         return _b("PRICE_PATTERNS", "FAVOURITE_DRIFT",
#             f"Price drifting to {ltp} · Losing market confidence")

#     if ltp < 2.0 and pdiff < -0.05:
#         return _b("PRICE_PATTERNS", "UNDERDOG_SURGE",
#             f"Price dropping to {ltp} · Market backing this team")

#     if abs(pdiff) < 0.05:
#         return _b("PRICE_PATTERNS", "PRICE_STABILIZE",
#             f"Price stable at {ltp} · Market balanced")

#     # ── NO PATTERN ───────────────────────────────────────────
#     return {
#         "pattern_name": "STABLE",
#         "pattern_category": "NONE",
#         "pattern_category_label": "No Pattern",
#         "pattern_detail": f"No significant pattern · Over {over}",
#         "pattern_description": "No significant pattern detected",
#         "price_direction": "NEUTRAL",
#         "avg_price_move": 0.0,
#         "historical_accuracy": 50,
#         "color": "gray",
#     }


# def _b(category: str, name: str, detail: str) -> dict:
#     cat = PATTERN_LIBRARY[category]
#     pat = cat["patterns"][name]
#     return {
#         "pattern_name": name,
#         "pattern_category": category,
#         "pattern_category_label": cat["label"],
#         "pattern_detail": detail,
#         "pattern_description": pat["description"],
#         "price_direction": pat["price_direction"],
#         "avg_price_move": pat["avg_price_move"],
#         "historical_accuracy": pat["accuracy"],
#         "color": cat["color"],
#     }


# def get_pattern_library() -> dict:
#     """
#     Returns full grouped pattern library.
#     Call once on page load for dashboard pattern panel.
#     """
#     return PATTERN_LIBRARY


# # ══════════════════════════════════════════════════════════════
# # HELPER FUNCTIONS
# # ══════════════════════════════════════════════════════════════

# def safe_float(value, default=0.0):
#     try:
#         if value is None or value == "":
#             return default
#         return float(value)
#     except (TypeError, ValueError):
#         return default


# def safe_int(value, default=0):
#     try:
#         if value is None or value == "":
#             return default
#         return int(value)
#     except (TypeError, ValueError):
#         return default


# def parse_score(score_str):
#     parts = str(score_str).split("/")
#     runs = int(parts[0]) if parts and str(parts[0]).isdigit() else 0
#     wickets = int(parts[1]) if len(parts) > 1 and str(parts[1]).isdigit() else 0
#     return runs, wickets


# def parse_over(over_str):
#     parts = str(over_str).split(".")
#     over = int(parts[0]) if parts and str(parts[0]).isdigit() else 0
#     ball = int(parts[1]) if len(parts) > 1 and str(parts[1]).isdigit() else 0
#     return over, ball


# def parse_recent(recent_str):
#     balls = str(recent_str).strip().split()
#     if not balls:
#         return 0, 0, 0, 0, 0, 0
#     last = balls[-1]
#     wicket = 1 if "W" in last.upper() else 0
#     runs = int(last) if last.isdigit() else 0
#     four = 1 if runs == 4 else 0
#     six = 1 if runs == 6 else 0
#     boundary = 1 if runs in [4, 6] else 0
#     dot = 1 if runs == 0 and wicket == 0 else 0
#     return runs, wicket, boundary, dot, six, four


# def has_cricket_data(cricket: dict) -> bool:
#     if not cricket:
#         return False
#     important_fields = [
#         cricket.get("score"), cricket.get("overs"),
#         cricket.get("latest_ball"), cricket.get("innings"),
#         cricket.get("b1_name"), cricket.get("state"), cricket.get("status"),
#     ]
#     return any(value not in [None, "", 0, "0"] for value in important_fields)


# def has_market_data(price: dict) -> bool:
#     if not price:
#         return False
#     return (
#         price.get("ltp") is not None
#         or price.get("prev_ltp") is not None
#         or price.get("tv") is not None
#     )


# def get_market_trend(price: dict) -> str:
#     ltp = safe_float(price.get("ltp"), None)
#     prev_ltp = safe_float(price.get("prev_ltp"), None)
#     if ltp is None or prev_ltp is None:
#         return "unknown"
#     if ltp > prev_ltp:
#         return "up"
#     if ltp < prev_ltp:
#         return "down"
#     return "stable"


# def get_market_momentum(price: dict) -> float:
#     ltp = safe_float(price.get("ltp"), None)
#     prev_ltp = safe_float(price.get("prev_ltp"), None)
#     if ltp is None or prev_ltp is None or prev_ltp == 0:
#         return 0.0
#     return round(((ltp - prev_ltp) / prev_ltp) * 100, 4)


# def build_market_only_prediction(price: dict) -> dict:
#     ltp = safe_float(price.get("ltp"), None)
#     prev_ltp = safe_float(price.get("prev_ltp"), None)
#     tv = safe_float(price.get("tv"), 0.0)
#     trend = get_market_trend(price)
#     momentum_pct = get_market_momentum(price)
#     signal = "WAIT"
#     confidence = 0.50
#     price_going = "STABLE"
#     reason = "Market-only fallback prediction"
#     if trend == "up":
#         signal = "LAY"
#         confidence = 0.58
#         price_going = "UP"
#         reason = "Market price rising"
#     elif trend == "down":
#         signal = "BACK"
#         confidence = 0.58
#         price_going = "DOWN"
#         reason = "Market price falling"
#     if tv > 10000:
#         confidence += 0.05
#     if abs(momentum_pct) >= 1.0:
#         confidence += 0.05
#     confidence = min(confidence, 0.95)
#     return {
#         "mode": "market_only",
#         "signal_source": "live_market",
#         "signal": signal,
#         "price_going": price_going,
#         "confidence": round(float(confidence), 4),
#         "p_back": None,
#         "p_lay": None,
#         "reason": reason,
#         "pattern": _b("PRICE_PATTERNS", "PRICE_STABILIZE", "Market only — no cricket data"),
#         "market_id": price.get("market_id"),
#         "runner_id": price.get("runner_id"),
#         "current_price": ltp,
#         "previous_price": prev_ltp,
#         "traded_volume": tv,
#         "trend": trend,
#         "price_momentum_pct": momentum_pct,
#         "features_used": {
#             "price": ltp or 0,
#             "price_change": round((ltp - prev_ltp), 4) if ltp and prev_ltp else 0,
#             "price_change_pct": round(((ltp - prev_ltp) / max(prev_ltp, 0.01)), 4) if ltp and prev_ltp else 0,
#             "price_momentum": 1 if trend == "up" else (-1 if trend == "down" else 0),
#             "traded_volume": tv,
#         },
#     }


# def build_features(cricket: dict, price: dict) -> dict:
#     score, wickets = parse_score(cricket.get("score", "0/0"))
#     over, ball = parse_over(cricket.get("overs", "0.0"))
#     crr = float(cricket.get("crr", 0) or 0)
#     rrr = float(cricket.get("rrr", 0) or 0)
#     inn = int(cricket.get("innings", 1) or 1)
#     last3 = float(cricket.get("last3_runs", 0) or 0)
#     last5 = float(cricket.get("last5_runs", 0) or 0)
#     wkts5 = float(cricket.get("last5_wkts", 0) or 0)
#     tgt = int(cricket.get("target", 0) or 0)
#     pp_runs = int(cricket.get("pp_runs", 0) or 0)
#     lr, lw, lb, ld, ls, lf = parse_recent(cricket.get("recent", ""))
#     ltp = float(price.get("ltp", 2.0) or 2.0)
#     prev_ltp = float(price.get("prev_ltp", ltp) or ltp)
#     pdiff = round(ltp - prev_ltp, 4)
#     balls_used = over * 6 + ball
#     balls_remaining = max(120 - balls_used, 1)
#     runs_remaining = max(tgt - score - 1, 0) if inn == 2 else 0
#     if inn == 2 and crr > 0:
#         run_rate_pressure = min(rrr / max(crr, 0.1), 5.0)
#     else:
#         run_rate_pressure = crr / 8.0
#     return {
#         "innings": inn, "over": over, "over_norm": over / 19.0,
#         "ball_in_over": ball, "ball_in_over_norm": ball / 5.0,
#         "ball_number": balls_used, "balls_used_pct": balls_used / 120.0,
#         "is_innings_2": 1 if inn == 2 else 0,
#         "score_before": score, "pp_runs": pp_runs,
#         "wickets_before": wickets, "wickets_in_hand": 10 - wickets,
#         "wicket_pressure": wickets / 10.0,
#         "runs_remaining": runs_remaining, "balls_remaining": balls_remaining,
#         "current_run_rate": crr, "required_rate": rrr,
#         "run_rate_pressure": run_rate_pressure,
#         "runs_per_ball_needed": runs_remaining / balls_remaining if inn == 2 else 0,
#         "batting_momentum": (last3 - 3.9) / 3.9,
#         "is_powerplay": 1 if over <= 5 else 0,
#         "is_middle": 1 if 6 <= over <= 14 else 0,
#         "is_death": 1 if over >= 15 else 0,
#         "last_ball_runs": lr, "last_ball_wicket": lw,
#         "last_ball_boundary": lb, "last_ball_six": ls,
#         "last_ball_four": lf, "last_ball_dot": ld,
#         "rolling_3_runs": last3, "rolling_6_runs": last5,
#         "rolling_3_wickets": wkts5, "rolling_6_dots": 0,
#         "rolling_6_boundaries": 0,
#         "pressure_index": (
#             (wickets / 10.0) * 0.4
#             + (min(run_rate_pressure, 3) / 3) * 0.3
#             + (min(wkts5 / 3, 1)) * 0.3
#         ),
#         "price": ltp, "implied_prob": 1 / max(ltp, 1.01),
#         "price_favorite": 1 if ltp < 1.5 else 0,
#         "price_even": 1 if 1.5 <= ltp <= 2.5 else 0,
#         "price_underdog": 1 if ltp > 2.5 else 0,
#         "price_change": pdiff, "price_change_pct": pdiff / max(prev_ltp, 0.01),
#         "price_volatility": 0,
#         "price_momentum": 1 if pdiff > 0 else (-1 if pdiff < 0 else 0),
#         "price_trend_3": pdiff, "batting_won_toss": 0,
#     }


# def predict_combined(cricket: dict, price: dict) -> dict:
#     features = build_features(cricket, price)
#     row = {col: features.get(col, 0) for col in feat_cols}
#     X = np.array([[row[col] for col in feat_cols]])
#     probs = model.predict_proba(X)[0]
#     p_up, p_down = probs[0], probs[1]
#     if p_down >= THRESHOLD:
#         signal, confidence, price_going = "BACK", p_down, "DOWN"
#         reason = "Price likely to DROP"
#     elif p_up >= THRESHOLD:
#         signal, confidence, price_going = "LAY", p_up, "UP"
#         reason = "Price likely to RISE"
#     else:
#         signal, confidence, price_going = "WAIT", max(p_up, p_down), "STABLE"
#         reason = "Not confident enough to signal"
#     return {
#         "mode": "combined",
#         "signal_source": "cricket+market_model",
#         "signal": signal,
#         "price_going": price_going,
#         "confidence": round(float(confidence), 4),
#         "p_back": round(float(p_down), 4),
#         "p_lay": round(float(p_up), 4),
#         "reason": reason,
#         "pattern": detect_pattern(features),
#         "features_used": row,
#     }


# def predict(*args, **kwargs) -> dict:
#     cricket, price = {}, {}
#     if len(args) == 1 and isinstance(args[0], dict):
#         cricket = args[0].get("cricket", {}) or {}
#         price = args[0].get("price", {}) or {}
#     elif len(args) >= 2:
#         cricket, price = args[0] or {}, args[1] or {}
#     else:
#         cricket = kwargs.get("cricket", {}) or {}
#         price = kwargs.get("price", {}) or {}
#     if has_cricket_data(cricket) and has_market_data(price):
#         return predict_combined(cricket, price)
#     if has_market_data(price):
#         return build_market_only_prediction(price)
#     return {}




import os
import json
import pickle
import numpy as np


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "betpredict_model.pkl")

with open(MODEL_PATH, "rb") as f:
    pkg = pickle.load(f)

model = pkg["model"]
feat_cols = pkg["feature_cols"]

THRESHOLD = 0.65


# ══════════════════════════════════════════════════════════════
# PATTERN LIBRARY — loaded from betapp/patterns_library.json
# Run update_patterns.py to regenerate with new data
# ══════════════════════════════════════════════════════════════

def _load_pattern_library() -> dict:
    """
    Load pattern library from JSON file.
    Primary location: betapp/patterns_library.json (relative to this file)
    Falls back to additional search paths if primary not found.
    JSON is generated by update_patterns.py from features_dataset.csv
    """
    search_paths = [
        os.path.join(BASE_DIR, "betapp", "patterns_library.json"),   # PRIMARY
        os.path.join(BASE_DIR, "patterns_library.json"),
        os.path.join(BASE_DIR, "data", "patterns_library.json"),
        os.path.join(BASE_DIR, "..", "data", "patterns_library.json"),
        os.path.join(BASE_DIR, "..", "data", "parsed", "patterns_library.json"),
    ]

    for path in search_paths:
        resolved = os.path.abspath(path)
        if os.path.exists(resolved):
            try:
                with open(resolved, "r") as f:
                    data = json.load(f)
                lib = data.get("library", data)
                total_patterns = sum(
                    len(c.get("patterns", {})) for c in lib.values()
                    if isinstance(c, dict)
                )
                print(f"[PatternLibrary] Loaded from {resolved} — {total_patterns} patterns")
                return lib
            except (json.JSONDecodeError, Exception) as e:
                print(f"[PatternLibrary] ERROR reading {resolved}: {e}")

    print(
        "[PatternLibrary] WARNING: patterns_library.json not found in any search path.\n"
        "  Searched:\n" + "\n".join(f"    - {os.path.abspath(p)}" for p in search_paths) +
        "\n  Run update_patterns.py to generate the file."
    )
    return {}


PATTERN_LIBRARY = _load_pattern_library()


# ══════════════════════════════════════════════════════════════
# DETECT PATTERN — priority order, strongest signal first
# ══════════════════════════════════════════════════════════════

def detect_pattern(features: dict) -> dict:

    over             = features.get("over", 0)
    is_powerplay     = features.get("is_powerplay", 0)
    is_middle        = features.get("is_middle", 0)
    is_death         = features.get("is_death", 0)
    is_innings_2     = features.get("is_innings_2", 0)
    last_ball_wicket = features.get("last_ball_wicket", 0)
    last_ball_six    = features.get("last_ball_six", 0)
    rolling_3_wkts   = features.get("rolling_3_wickets", 0)
    rolling_3_runs   = features.get("rolling_3_runs", 0)
    rolling_6_runs   = features.get("rolling_6_runs", 0)
    rolling_6_dots   = features.get("rolling_6_dots", 0)
    rolling_6_bdry   = features.get("rolling_6_boundaries", 0)
    batting_momentum = features.get("batting_momentum", 0)
    wickets_before   = features.get("wickets_before", 0)
    wickets_in_hand  = features.get("wickets_in_hand", 10)
    crr              = features.get("current_run_rate", 0)
    rrr              = features.get("required_rate", 0)
    ltp              = features.get("price", 2.0)
    pdiff            = features.get("price_trend_3", 0)
    pp_runs          = features.get("pp_runs", 0)

    # ── WICKET PATTERNS ──────────────────────────────────────
    if wickets_before >= 7 and is_death:
        return _b("WICKET_PATTERNS", "TAIL_EXPOSED",
            f"{wickets_before} wickets down · Death overs · {int(wickets_in_hand)} left")

    if rolling_3_wkts >= 3 and is_middle:
        return _b("WICKET_PATTERNS", "MIDDLE_COLLAPSE",
            f"{int(rolling_3_wkts)} wickets in middle overs · Over {over}")

    if rolling_3_wkts >= 3:
        return _b("WICKET_PATTERNS", "WICKET_COLLAPSE",
            f"{int(rolling_3_wkts)} wickets last 3 overs · {int(wickets_in_hand)} in hand")

    if last_ball_wicket == 1 and is_powerplay:
        return _b("WICKET_PATTERNS", "POWERPLAY_WICKET",
            f"Wicket in powerplay · Over {over}")

    if last_ball_wicket == 1:
        return _b("WICKET_PATTERNS", "WICKET_SPIKE",
            f"Wicket just fell · Over {over} · {int(wickets_in_hand)} left")

    # ── PRESSURE PATTERNS ────────────────────────────────────
    if is_innings_2 and rrr > 0 and crr > 0 and (rrr - crr) >= 2:
        return _b("PRESSURE_PATTERNS", "CHASE_CRISIS",
            f"Required {rrr:.1f} vs Current {crr:.1f} · Chase behind")

    if is_innings_2 and rrr > 0 and crr > 0 and (crr - rrr) >= 2:
        return _b("PRESSURE_PATTERNS", "CHASE_CONTROLLED",
            f"Current {crr:.1f} above required {rrr:.1f} · Chase in control")

    if is_middle and rrr > 12:
        return _b("PRESSURE_PATTERNS", "RUN_RATE_DANGER",
            f"Required rate {rrr:.1f} · Middle overs · High pressure")

    if rolling_6_dots >= 5:
        return _b("PRESSURE_PATTERNS", "DOT_BALL_TRAP",
            f"{int(rolling_6_dots)} dot balls in last 6 · Batting stifled")

    if rolling_6_dots >= 4:
        return _b("PRESSURE_PATTERNS", "PRESSURE_BUILD",
            f"{int(rolling_6_dots)} dot balls in last 6 · Pressure mounting")

    # ── PHASE PATTERNS ────────────────────────────────────────
    if is_death and over >= 17 and rolling_6_runs >= 15:
        return _b("PHASE_PATTERNS", "DEATH_CARNAGE",
            f"{rolling_6_runs:.0f} runs in last 2 overs · Over {over}")

    if is_powerplay and pp_runs >= 50 and wickets_before <= 1:
        return _b("PHASE_PATTERNS", "POWERPLAY_DOMINANT",
            f"{pp_runs} runs in powerplay · {wickets_before} wicket(s) · Dominant")

    if is_middle and rolling_6_runs < 20 and 2 <= wickets_before <= 4:
        return _b("PHASE_PATTERNS", "MIDDLE_GRIND",
            f"Slow middle overs · {rolling_6_runs:.0f} runs · {wickets_before} wickets")

    # ── BATTING PATTERNS ─────────────────────────────────────
    if rolling_6_bdry >= 3 and last_ball_six >= 1:
        return _b("BATTING_PATTERNS", "SIX_STORM",
            f"Sixes flying · {int(rolling_6_bdry)} boundaries · Over {over}")

    if rolling_6_bdry >= 3:
        return _b("BATTING_PATTERNS", "BOUNDARY_BURST",
            f"{int(rolling_6_bdry)} boundaries in last 6 · Over {over}")

    if is_powerplay and rolling_6_bdry >= 2:
        return _b("BATTING_PATTERNS", "POWERPLAY_SURGE",
            f"{int(rolling_6_bdry)} boundaries in powerplay · Strong start")

    if is_death and wickets_before >= 5 and batting_momentum > 0.5:
        return _b("BATTING_PATTERNS", "DEATH_REVIVAL",
            f"Over {over} · {wickets_before} wickets but scoring · Revival")

    if is_death and batting_momentum > 1.0:
        return _b("BATTING_PATTERNS", "DEATH_SLOG",
            f"Over {over} · Death · {rolling_3_runs:.0f} runs last 3 overs")

    if batting_momentum > 2.0 and rolling_3_runs >= 15:
        return _b("BATTING_PATTERNS", "BATTING_SURGE",
            f"{rolling_3_runs:.0f} runs in last 3 overs · Strong momentum")

    # ── PRICE PATTERNS ────────────────────────────────────────
    if ltp > 2.5 and pdiff > 0.05:
        return _b("PRICE_PATTERNS", "FAVOURITE_DRIFT",
            f"Price drifting to {ltp} · Losing market confidence")

    if ltp < 2.0 and pdiff < -0.05:
        return _b("PRICE_PATTERNS", "UNDERDOG_SURGE",
            f"Price dropping to {ltp} · Market backing this team")

    if abs(pdiff) < 0.05:
        return _b("PRICE_PATTERNS", "PRICE_STABILIZE",
            f"Price stable at {ltp} · Market balanced")

    # ── NO PATTERN ───────────────────────────────────────────
    return {
        "pattern_name": "STABLE",
        "pattern_category": "NONE",
        "pattern_category_label": "No Pattern",
        "pattern_detail": f"No significant pattern · Over {over}",
        "pattern_description": "No significant pattern detected",
        "price_direction": "NEUTRAL",
        "avg_price_move": 0.0,
        "historical_accuracy": 50,
        "color": "gray",
    }


def _b(category: str, name: str, detail: str) -> dict:
    """
    Build a pattern result dict from PATTERN_LIBRARY.
    Gracefully falls back if the library is missing or incomplete
    so detect_pattern never raises a KeyError.
    """
    cat = PATTERN_LIBRARY.get(category) if PATTERN_LIBRARY else None

    # Category not found — return safe fallback
    if not cat or not isinstance(cat, dict):
        return {
            "pattern_name": name,
            "pattern_category": category,
            "pattern_category_label": category.replace("_", " ").title(),
            "pattern_detail": detail,
            "pattern_description": f"{name.replace('_', ' ').title()} detected",
            "price_direction": "NEUTRAL",
            "avg_price_move": 0.0,
            "historical_accuracy": 50,
            "color": "gray",
        }

    pat = cat.get("patterns", {}).get(name) if isinstance(cat.get("patterns"), dict) else None

    # Pattern name not found within category — return partial fallback
    if not pat or not isinstance(pat, dict):
        return {
            "pattern_name": name,
            "pattern_category": category,
            "pattern_category_label": cat.get("label", category.replace("_", " ").title()),
            "pattern_detail": detail,
            "pattern_description": f"{name.replace('_', ' ').title()} detected",
            "price_direction": "NEUTRAL",
            "avg_price_move": 0.0,
            "historical_accuracy": 50,
            "color": cat.get("color", "gray"),
        }

    # Full data available
    return {
        "pattern_name": name,
        "pattern_category": category,
        "pattern_category_label": cat.get("label", category),
        "pattern_detail": detail,
        "pattern_description": pat.get("description", f"{name} detected"),
        "price_direction": pat.get("price_direction", "NEUTRAL"),
        "avg_price_move": pat.get("avg_price_move", 0.0),
        "historical_accuracy": pat.get("accuracy", 50),
        "color": cat.get("color", "gray"),
    }


def get_pattern_library() -> dict:
    """
    Returns full grouped pattern library.
    Call once on page load for dashboard pattern panel.
    """
    return PATTERN_LIBRARY


# ══════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ══════════════════════════════════════════════════════════════

def safe_float(value, default=0.0):
    try:
        if value is None or value == "":
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def safe_int(value, default=0):
    try:
        if value is None or value == "":
            return default
        return int(value)
    except (TypeError, ValueError):
        return default


def parse_score(score_str):
    """
    Parse score string like '139/4' into (runs, wickets).
    Also handles plain integer score (e.g. 139) — wickets will be 0,
    caller should supplement from cricket['wickets'] if available.
    """
    parts = str(score_str).split("/")
    runs = int(parts[0]) if parts and str(parts[0]).isdigit() else 0
    wickets = int(parts[1]) if len(parts) > 1 and str(parts[1]).isdigit() else 0
    return runs, wickets


def parse_over(over_str):
    parts = str(over_str).split(".")
    over = int(parts[0]) if parts and str(parts[0]).isdigit() else 0
    ball = int(parts[1]) if len(parts) > 1 and str(parts[1]).isdigit() else 0
    return over, ball


def parse_recent(recent_str):
    """
    Parse the last ball from recent string (e.g. '6 4 1 1 1').
    Returns stats for the LAST ball only.
    """
    balls = str(recent_str).strip().split()
    if not balls:
        return 0, 0, 0, 0, 0, 0
    last = balls[-1]
    wicket = 1 if "W" in last.upper() else 0
    runs = int(last) if last.isdigit() else 0
    four = 1 if runs == 4 else 0
    six = 1 if runs == 6 else 0
    boundary = 1 if runs in [4, 6] else 0
    dot = 1 if runs == 0 and wicket == 0 else 0
    return runs, wicket, boundary, dot, six, four


def parse_recent_full(recent_str: str):
    """
    Parse full recent balls string (e.g. '6 4 1 1 1') for rolling stats.
    Returns (dots, boundaries) across ALL balls in the string.

    Ball tokens:
      - digit        → scored runs (0 = dot, 4/6 = boundary)
      - W / Wd / Wb  → wicket (counts as dot for scoring purposes)
      - wd / nb      → extras (not a dot, not a boundary)
    """
    balls = str(recent_str).strip().split()
    dots = 0
    boundaries = 0
    for b in balls:
        upper = b.upper()
        if "W" in upper:
            # Wicket ball — dot for batting purposes
            dots += 1
        elif b.isdigit():
            runs = int(b)
            if runs == 0:
                dots += 1
            if runs in [4, 6]:
                boundaries += 1
        # extras (wd, nb) — skip, neither dot nor boundary
    return dots, boundaries


def has_cricket_data(cricket: dict) -> bool:
    if not cricket:
        return False
    important_fields = [
        cricket.get("score"), cricket.get("overs"),
        cricket.get("latest_ball"), cricket.get("innings"),
        cricket.get("b1_name"), cricket.get("state"), cricket.get("status"),
    ]
    return any(value not in [None, "", 0, "0"] for value in important_fields)


def has_market_data(price: dict) -> bool:
    if not price:
        return False
    return (
        price.get("ltp") is not None
        or price.get("prev_ltp") is not None
        or price.get("tv") is not None
    )


def get_market_trend(price: dict) -> str:
    ltp = safe_float(price.get("ltp"), None)
    prev_ltp = safe_float(price.get("prev_ltp"), None)
    if ltp is None or prev_ltp is None:
        return "unknown"
    if ltp > prev_ltp:
        return "up"
    if ltp < prev_ltp:
        return "down"
    return "stable"


def get_market_momentum(price: dict) -> float:
    ltp = safe_float(price.get("ltp"), None)
    prev_ltp = safe_float(price.get("prev_ltp"), None)
    if ltp is None or prev_ltp is None or prev_ltp == 0:
        return 0.0
    return round(((ltp - prev_ltp) / prev_ltp) * 100, 4)


def build_market_only_prediction(price: dict) -> dict:
    ltp = safe_float(price.get("ltp"), None)
    prev_ltp = safe_float(price.get("prev_ltp"), None)
    tv = safe_float(price.get("tv"), 0.0)
    trend = get_market_trend(price)
    momentum_pct = get_market_momentum(price)
    signal = "WAIT"
    confidence = 0.50
    price_going = "STABLE"
    reason = "Market-only fallback prediction"
    if trend == "up":
        signal = "LAY"
        confidence = 0.58
        price_going = "UP"
        reason = "Market price rising"
    elif trend == "down":
        signal = "BACK"
        confidence = 0.58
        price_going = "DOWN"
        reason = "Market price falling"
    if tv > 10000:
        confidence += 0.05
    if abs(momentum_pct) >= 1.0:
        confidence += 0.05
    confidence = min(confidence, 0.95)
    return {
        "mode": "market_only",
        "signal_source": "live_market",
        "signal": signal,
        "price_going": price_going,
        "confidence": round(float(confidence), 4),
        "p_back": None,
        "p_lay": None,
        "reason": reason,
        "pattern": _b("PRICE_PATTERNS", "PRICE_STABILIZE", "Market only — no cricket data"),
        "market_id": price.get("market_id"),
        "runner_id": price.get("runner_id"),
        "current_price": ltp,
        "previous_price": prev_ltp,
        "traded_volume": tv,
        "trend": trend,
        "price_momentum_pct": momentum_pct,
        "features_used": {
            "price": ltp or 0,
            "price_change": round((ltp - prev_ltp), 4) if ltp and prev_ltp else 0,
            "price_change_pct": round(((ltp - prev_ltp) / max(prev_ltp, 0.01)), 4) if ltp and prev_ltp else 0,
            "price_momentum": 1 if trend == "up" else (-1 if trend == "down" else 0),
            "traded_volume": tv,
        },
    }


def build_features(cricket: dict, price: dict) -> dict:
    # ── Score & Wickets ───────────────────────────────────────
    # parse_score handles "139/4" format; if score is plain int (139),
    # wickets will be 0 — supplement from explicit 'wickets' key.
    score, wickets = parse_score(cricket.get("score", "0/0"))
    if wickets == 0 and cricket.get("wickets") not in [None, "", 0]:
        wickets = safe_int(cricket.get("wickets"), 0)

    # ── Overs ─────────────────────────────────────────────────
    over, ball = parse_over(cricket.get("overs", "0.0"))

    # ── Run rates ─────────────────────────────────────────────
    crr = float(cricket.get("crr", 0) or 0)
    rrr = float(cricket.get("rrr", 0) or 0)

    # ── Innings & match state ─────────────────────────────────
    inn = int(cricket.get("innings", 1) or 1)
    last3 = float(cricket.get("last3_runs", 0) or 0)
    last5 = float(cricket.get("last5_runs", 0) or 0)
    wkts5 = float(cricket.get("last5_wkts", 0) or 0)
    tgt = int(cricket.get("target", 0) or 0)
    pp_runs = int(cricket.get("pp_runs", 0) or 0)

    # ── Last ball ─────────────────────────────────────────────
    lr, lw, lb, ld, ls, lf = parse_recent(cricket.get("recent", ""))

    # ── Rolling dots & boundaries from full recent string ─────
    # FIX: was hardcoded to 0; now properly parsed from recent balls
    rolling_6_dots, rolling_6_bdry = parse_recent_full(cricket.get("recent", ""))

    # ── Price ─────────────────────────────────────────────────
    ltp = float(price.get("ltp", 2.0) or 2.0)
    prev_ltp = float(price.get("prev_ltp", ltp) or ltp)
    pdiff = round(ltp - prev_ltp, 4)

    # ── Derived ball/run counts ───────────────────────────────
    balls_used = over * 6 + ball
    balls_remaining = max(120 - balls_used, 1)
    runs_remaining = max(tgt - score - 1, 0) if inn == 2 else 0

    if inn == 2 and crr > 0:
        run_rate_pressure = min(rrr / max(crr, 0.1), 5.0)
    else:
        run_rate_pressure = crr / 8.0

    return {
        "innings": inn, "over": over, "over_norm": over / 19.0,
        "ball_in_over": ball, "ball_in_over_norm": ball / 5.0,
        "ball_number": balls_used, "balls_used_pct": balls_used / 120.0,
        "is_innings_2": 1 if inn == 2 else 0,
        "score_before": score, "pp_runs": pp_runs,
        "wickets_before": wickets,                      # ✅ FIX: now reads actual wickets
        "wickets_in_hand": 10 - wickets,
        "wicket_pressure": wickets / 10.0,
        "runs_remaining": runs_remaining, "balls_remaining": balls_remaining,
        "current_run_rate": crr, "required_rate": rrr,
        "run_rate_pressure": run_rate_pressure,
        "runs_per_ball_needed": runs_remaining / balls_remaining if inn == 2 else 0,
        "batting_momentum": (last3 - 3.9) / 3.9,
        "is_powerplay": 1 if over <= 5 else 0,
        "is_middle": 1 if 6 <= over <= 14 else 0,
        "is_death": 1 if over >= 15 else 0,
        "last_ball_runs": lr, "last_ball_wicket": lw,
        "last_ball_boundary": lb, "last_ball_six": ls,
        "last_ball_four": lf, "last_ball_dot": ld,
        "rolling_3_runs": last3, "rolling_6_runs": last5,
        "rolling_3_wickets": wkts5,
        "rolling_6_dots": rolling_6_dots,               # ✅ FIX: was hardcoded 0
        "rolling_6_boundaries": rolling_6_bdry,         # ✅ FIX: was hardcoded 0
        "pressure_index": (
            (wickets / 10.0) * 0.4
            + (min(run_rate_pressure, 3) / 3) * 0.3
            + (min(wkts5 / 3, 1)) * 0.3
        ),
        "price": ltp, "implied_prob": 1 / max(ltp, 1.01),
        "price_favorite": 1 if ltp < 1.5 else 0,
        "price_even": 1 if 1.5 <= ltp <= 2.5 else 0,
        "price_underdog": 1 if ltp > 2.5 else 0,
        "price_change": pdiff, "price_change_pct": pdiff / max(prev_ltp, 0.01),
        "price_volatility": 0,
        "price_momentum": 1 if pdiff > 0 else (-1 if pdiff < 0 else 0),
        "price_trend_3": pdiff, "batting_won_toss": 0,
    }


def predict_combined(cricket: dict, price: dict) -> dict:
    features = build_features(cricket, price)
    row = {col: features.get(col, 0) for col in feat_cols}
    X = np.array([[row[col] for col in feat_cols]])
    probs = model.predict_proba(X)[0]
    p_up, p_down = probs[0], probs[1]
    if p_down >= THRESHOLD:
        signal, confidence, price_going = "BACK", p_down, "DOWN"
        reason = "Price likely to DROP"
    elif p_up >= THRESHOLD:
        signal, confidence, price_going = "LAY", p_up, "UP"
        reason = "Price likely to RISE"
    else:
        signal, confidence, price_going = "WAIT", max(p_up, p_down), "STABLE"
        reason = "Not confident enough to signal"
    return {
        "mode": "combined",
        "signal_source": "cricket+market_model",
        "signal": signal,
        "price_going": price_going,
        "confidence": round(float(confidence), 4),
        "p_back": round(float(p_down), 4),
        "p_lay": round(float(p_up), 4),
        "reason": reason,
        "pattern": detect_pattern(features),
        "features_used": row,
    }


def predict(*args, **kwargs) -> dict:
    cricket, price = {}, {}
    if len(args) == 1 and isinstance(args[0], dict):
        cricket = args[0].get("cricket", {}) or {}
        price = args[0].get("price", {}) or {}
    elif len(args) >= 2:
        cricket, price = args[0] or {}, args[1] or {}
    else:
        cricket = kwargs.get("cricket", {}) or {}
        price = kwargs.get("price", {}) or {}
    if has_cricket_data(cricket) and has_market_data(price):
        return predict_combined(cricket, price)
    if has_market_data(price):
        return build_market_only_prediction(price)
    return {}